### ISSUE TITLE
Syntax error: word unexpected (expecting ")") in Void Linux

### ISSUE THREAD

**Issue by thegarlynch** [johang/vlc-bittorrent#48] opened 2022-05-26 02:47 UTC
when i try to build it. this error comes up

checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gawk... gawk
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/sbin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of g++... gcc3
checking for pkg-config... /usr/sbin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for vlc-plugin >= 3.0.0... yes
checking for libtorrent-rasterbar >= 1.0.0... yes
./configure: 4038: Syntax error: word unexpected (expecting ")")

**Comment by johang** [comment] 2022-05-28 22:28
Which shell are you using?

**Comment by thegarlynch** [comment] 2022-06-02 09:59
zsh

**Comment by johang** [comment] 2022-06-04 16:52
Unable to reproduce this. Do you have steps how to reproduce this in Docker?

**Comment by petterreinholdtsen** [comment] 2023-12-20 07:23
@thegarlynch Perhaps you can share what is written around line 4038 in your edition of configure, to give a better idea about exactly which code is failing?  Are you sure you are not running configure with zsh?

**Comment by petterreinholdtsen** [comment] 2024-08-20 16:08
And for the record, this is what my line 4038 look like:

```
   4036 
   4037 # Check whether --enable-dependency-tracking was given.
   4038 if test ${enable_dependency_tracking+y}
   4039 then :
   4040   enableval=$enable_dependency_tracking;
   4041 fi
   4042 
```

Without more useful information from the requestor, I believe this issue can be closed as unsolvable.

**Closed** 2024-08-20 18:34 UTC
